### ISSUE TITLE
README SCREENSHOTS

### ISSUE THREAD

**Issue by hmparsons-sde** [nss-evening-cohort-14/gitsub-e14-team-2-electric-boogaloo#86]
![m0nica](https://user-images.githubusercontent.com/67122062/107985961-beae4d80-6f90-11eb-9d14-438f4599f14c.png)

![Final About Me](https://user-images.githubusercontent.com/67122062/107975130-3ecab800-6f7d-11eb-94d4-02c1dc5a8ab7.png)

**Comment by Gabrielle-Tobermann** [comment]
![gitsub-1](https://user-images.githubusercontent.com/76187279/107995743-a855c100-6f93-11eb-8e0f-e096f96632a3.png)
![gitsub-2](https://user-images.githubusercontent.com/76187279/107995750-abe94800-6f93-11eb-94f5-05757c565f12.png)
![gitsub-3](https://user-images.githubusercontent.com/76187279/107995760-aee43880-6f93-11eb-82cf-5e96cba6df3b.png)
![gitsub-4](https://user-images.githubusercontent.com/76187279/107995798-c28f9f00-6f93-11eb-868d-721dcf3c410d.png)
